project:
  type: website
  output-dir: docs
  
website:
  title: "R, Rasch, etc"
  site-url: "https://pgmj.github.io"
  repo-url: https://github.com/pgmj/pgmj.github.io
  open-graph: true
  comments:
    giscus:
      repo: pgmj/pgmj.github.io
  twitter-card: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Note:** The RISEkbmRasch vignette has new sections on item fit visualization, LR DIF tests, and person fit"
    type: primary
    position: below-navbar
  navbar: 
    search: true
    background: "#009ca6"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - raschrvignette/RaschRvign.qmd
      - about.qmd
      - text: "Blog"  
        menu:
         - parameterizedQ.qmd
         - latentResp/LatentResponse.qmd
         - SkolverketAPI/skolverketapi.qmd
         - powerviz.qmd
         - datawrangling.qmd
      - icon: github
        href: https://github.com/pgmj/pgmj.github.io
        aria-label: GitHub

format:
  html:
    theme: 
      - materia
      - custom.scss
    css: styles.css
    toc: true
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    code-overflow: wrap
    code-tools: true
    code-fold: show
    code-link: true
    number-sections: true
    fig-dpi: 150
    layout-align: left
    page-layout: full
    linestretch: 1.6
    license: CC BY
    toc-title: 'Table of contents'