project:
  type: website
  output-dir: docs
  
website:
  title: "R, Rasch, etc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - raschrvignette/RaschRvign.qmd
      - about.qmd

format:
  html:
    theme: 
      - materia
      - custom.scss
    css: styles.css
    toc: true
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    code-overflow: wrap
    code-tools: true
    code-fold: show
    number-sections: true
    fig-dpi: 150
    layout-align: left
    page-layout: full
    linestretch: 1.6
    license: CC BY